TRAIN:
  LEARNING_RATE: 0.01
  MOMENTUM: 0.9
  BATCH_SIZE: 32
  #orginal 16
  MAX_EPOCH: 50
  SCHEDULER: step # adam
  IS_PRETRAINED: False
  PRETRAINED_MODEL_PATH: checkpoints/pointnet2_MT.t7
  #  - checkpoints/MC0.t7
  #  - checkpoints/MC1.t7
  #  - checkpoints/MC2.t7
  #  - checkpoints/MC3.t7
  #  - checkpoints/MC4.t7
  OUTPUT_DIR: log/
  DROPOUT_RATE: 0.5
  CONSISTENCY_LOSS: False
  CONSISTENCY_WEIGHTS:
    - 0.05
    - 0.05
    - 0.05
    - 0.05
  LOSS_WEIGHTS:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0


DEVICES:
  GPU_ID: 
    - 0
  SEED: 1

